{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bayesforecast
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bayesforecast_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bayesforecast/bayesforecast_{{ version }}.tar.gz
  sha256: 89d5b3adf3cec44f64211bc6854b8fc95db794b35e355d159d3c28e960472c5d

build:
  number: 0
  skip: true  # [r_base == "3.6"]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh >=1.66.0
    - r-mass
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-rcppparallel >=5.0.1
    - r-stanheaders
    - r-astsa
    - r-bayesplot >=1.5.0
    - r-bridgesampling >=0.3_0
    - r-forecast
    - r-ggplot2
    - r-gridextra
    - r-loo >=2.2.0
    - r-lubridate
    - r-prophet
    - r-rstan >=2.18.1
    - r-rstantools >=2.0.0
    - r-zoo
  run:
    - r-base
    #- r-bh >=1.66.0
    - r-mass
    - r-rcpp >=0.12.0
    - r-rcppeigen >=0.3.3.3.0
    - r-rcppparallel >=5.0.1
    #- r-stanheaders
    - r-astsa
    - r-bayesplot >=1.5.0
    - r-bridgesampling >=0.3_0
    - r-forecast
    - r-ggplot2
    - r-gridextra
    - r-loo >=2.2.0
    - r-lubridate
    - r-prophet
    - r-rstan >=2.18.1
    - r-rstantools >=2.0.0
    - r-zoo

test:
  commands:
    - $R -e "library('bayesforecast')"           # [not win]
    - "\"%R%\" -e \"library('bayesforecast')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bayesforecast
  license: GPL-2.0-or-later
  summary: "Fit Bayesian time series models using 'Stan' for full Bayesian inference. A wide range of distributions and models are supported, allowing users to fit Seasonal ARIMA, ARIMAX, Dynamic Harmonic Regression, GARCH, t-student innovation GARCH models, asymmetric GARCH, Random Walks, stochastic volatility models for
    univariate time series.  Prior specifications are flexible and explicitly encourage users to apply prior distributions that actually reflect their beliefs. Model fit can easily be assessed and compared with typical visualization methods, information criteria such as loglik, AIC, BIC WAIC, Bayes factor and leave-one-out
    cross-validation methods. References: Hyndman (2017) <doi:10.18637/jss.v027.i03>; Carpenter et al. (2017) <doi:10.18637/jss.v076.i01>."
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
